// Code generated by goctl. DO NOT EDIT!
// Source: greet.proto

package server

import (
	"context"

	"black/rpc/internal/greet"
	"black/rpc/internal/logic"
	"black/rpc/internal/svc"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

func (s *GreetServer) Ping(ctx context.Context, in *greet.Request) (*greet.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *GreetServer) SayHello(ctx context.Context, in *greet.SayRequest) (*greet.SayResponse, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
